'\" t
.\"     Title: phpcompatinfo
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/28/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PHPCOMPATINFO" "1" "05/28/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
phpcompatinfo \- parse any data source to find out the minimum version and extensions required for it to run
.SH "SYNOPSIS"
.sp
\fBphpcompatinfo\fR [\fIOPTIONS\fR] \fICOMMAND\fR [\fIOPTS\fR] [\fIDATASOURCE\fR]
.SH "DESCRIPTION"
.sp
The phpcompatinfo(1) command parse any \fIDATASOURCE\fR to find out the minimum PHP version and extensions required\&.
.SH "OPTIONS"
.PP
\fB\-\-configuration\fR=\fIXMLFILE\fR
.RS 4
Read configuration options from
\fIXMLFILE\fR\&. All command line options will overrides those that are defined in this xml file\&.
.RE
.PP
\fB\-\-no\-configuration\fR
.RS 4
Ignore default configuration files:
\fIphpcompatinfo\&.xml\fR,
\fIphpcompatinfo\&.xml\&.dist\fR\&.
.RE
.PP
\fB\-d, \-\-ini\-set\fR=\fIINI_SET\fR
.RS 4
Sets a php\&.ini directive value\&. This option may be specified more than once\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Verbosely print processing information and warning messages\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[\fITOPIC\fR] \-h, \-\-help*:: Print help TOPIC\&.
\fItopic\fR\fB\-\-help\fR
will print help content about a topic,
\fB\-\-help\fR
summarizes phpcompatinfo syntax\&.
.RE
.RE
.PP
\fB\-\-version\fR
.RS 4
Print program version number\&.
.RE
.SH "PRINT COMMAND"
.sp
The phpcompatinfo(1) \fIPRINT\fR command is used to find out minimum php version to run data source code provided\&. Syntax:
.sp
.if n \{\
.RS 4
.\}
.nf
phpcompatinfo print [OPTION] DATA_SOURCE
.fi
.if n \{\
.RE
.\}
.sp
Where:
.PP
\fBOPTION\fR
.RS 4
phpcompatinfo(1)
\fB\-\-report\fR
option specifying the type of result to print on stdout\&. See
\fB\-\-help\-report\fR
option for valid choices\&.
.RE
.PP
\fBDATA_SOURCE\fR
.RS 4
The source path to scan\&.
.RE
.sp
The commands perform as follows:
.PP
\fBprint\fR
.RS 4
Print report on stdout or into a file if
\fB\-\-report\-file\fR
option is in effect\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error; configuration error; unexpected error)\&.
.RE
.SH "BUGS"
.sp
Report any issue at https://github\&.com/llaville/php\-compat\-info/issues
.SH "AUTHORS"
.sp
PHP_CompatInfo was originally written by Davey Shafik in 2004\&.
.sp
Remi Collet, contributor of many extensions reference and unit tests, joined the project since version 2\&.0\&.0RC2
.sp
This CLI version was introduced and written by Laurent Laville\&.
.SH "SEE ALSO"
.sp
Main web site: http://php5\&.laurent\-laville\&.org/compatinfo/
.SH "COPYRIGHT"
.sp
Copyright (C) 2010\-2013 Laurent Laville\&.
.SH "LICENSE"
.sp
Free use of this software is granted under the terms of the BSD 3\-clause license\&.
