= PHP CompatInfo

**PHP CompatInfo** is a library that
can find the minimum version and the extensions required for a piece of code to run.

It is distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

Follow development on the http://php5.laurent-laville.org/compatinfo/blog[official Blog].

Have a look on https://github.com/llaville/php-compat-info/releases/tag/3.7.4[tag 3.7.4] for previous stable API 3.0

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpcompatinfo-4.1.0.phar[4.1.0]
* install via https://packagist.org/packages/bartlett/php-compatinfo/[packagist] the current source dev-master or the stable version 4.1.0

== Documentation

The documentation for PHP CompatInfo 4.1
in http://php5.laurent-laville.org/compatinfo/manual/4.1/en/[English]
is available online or downloadable offline to read it later (multiple formats).

AsciiDoc source code is available on `docs` folder of the repository.

== Contribute

Contributions to source code and its documentation are always welcome.

As a developer, I'm always happy when I have more information as possible to check and find out issues.
This is the reason why I've created a https://github.com/llaville/phpunit-LoggerTestListener[PHPUnit TestSuite Listener for compatible PSR-3 Loggers].

If you want to use it, then :

- install the component via Composer

[source,bash]
----
$ php composer.phar require bartlett/phpunit-loggertestlistener=~1.3
----

- create a `phpunit.xml` file with at least following contents :

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    backupGlobals="true"
    backupStaticAttributes="false"
    bootstrap="tests/bootstrap.dev.php"
    colors="false"
    stopOnError="false"
    stopOnFailure="false"
    stopOnIncomplete="false"
    stopOnRisky="false"
    stopOnSkipped="false"
    verbose="false"
>
    <filter>
        <whitelist>
        <directory suffix=".php">src/</directory>
        </whitelist>
    </filter>
    <listeners>
        <listener class="Bartlett\LoggerTestListener">
            <arguments>
                <object class="Psr3Logger" />
            </arguments>
        </listener>
    </listeners>
    <testsuites>
        <testsuite name="CompatInfo Test Suite">
            <directory suffix="Test.php">tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
----

- configure your PSR-3 logger in the `tests\bootstrap.dev.php` file

NOTE: By default will log all tests in local file `/var/logs/phpcompatinfo.log`
and send a Growl notification of Test Suites summary when ended (if growl server is running).
