= PHP CompatInfo

**PHP CompatInfo** is a library that
can find the minimum version and the extensions required for a piece of code to run.

It is distributed as source code (install via composer) and a PHAR version
that bundles all dependencies in a single file.

Follow development on the http://php5.laurent-laville.org/compatinfo/blog[official Blog].

Have a look on https://github.com/llaville/php-compat-info/tree/4.5[branch 4.5] for previous stable API 4.x

CAUTION: Branch 4.5 will not accept any more any feature requests. Consider to ask your request on branch 5.0 now !

== Install

You can either :

* download the phar version http://bartlett.laurent-laville.org/get/phpcompatinfo-5.0.0.phar[5.0.0]
* install via https://packagist.org/packages/bartlett/php-compatinfo/[packagist] the current source dev-master or the stable version 5.0.0

== Documentation

The documentation for PHP CompatInfo 5.0
in http://php5.laurent-laville.org/compatinfo/manual/5.0/en/[English]
is available online or downloadable offline to read it later (multiple formats available).

AsciiDoc source code is available on `docs` folder of the repository.

== Contribute

Contributions to source code and its documentation are always welcome.

== Authors

* Laurent Laville

== License

This handler is licensed under the BSD-3-clauses License - see the `LICENSE` file for details
