ifndef::basebackend-docbook[]

= Handle Results
:description: Learn how to explore and exploit parsing results.
include::revision.asciidoc[]
include::attributes.asciidoc[]

endif::basebackend-docbook[]

[role="lead"]
Whatever SAPI you use, all metrics (for each analysers asked) are available
at end of parse, in the same format.

With CLI, and [label label-primary]#CompatInfo# source code,
to get a compatibility report, you have to invoke the following command :
[source,bash]
----
$ phpcompatinfo analyser:run /home/github/php-compat-info/src
----
With others SAPI, use example {rawbaseurl}/examples/api_analyser_run.php

and you should obtain something like this :

[role="output"]
====
----
include::compatibility_analysis.out.asciidoc[]
----
====

This is the default render. But, if you want to compare with other SAPI,
activate the debug verbose mode (`-vvv`) to get the raw response.
You should obtain something like this :

[role="output"]
====
----
include::compatibility_analysis.raw.asciidoc[]
----
====

* First entry in array is the list of parsed `files`
* Second entry in array is the `compatibility` analyser result

Each analyser as its own data structure and results, but you will always get the fully qualified
class name that identify origin of analyser used.

.Example with two analysers (`structure` and `compatibility`)
[source,bash]
----
$ phpcompatinfo analyser:run /home/github/php-compat-info/src structure compatibility
----

[role="output"]
====
----
Raw response
Array
(
    [files] => Array
        (
            ...
        )

    [Bartlett\Reflect\Analyser\StructureAnalyser] => Array
        (
            ...
        )

    [Bartlett\CompatInfo\Analyser\CompatibilityAnalyser] => Array
        (
            ...
        )

)
----
====
