= Plugins
:description: How to extend the features list.
include::revision.asciidoc[]
include::attributes.asciidoc[]


== Events

[role="lead"]
CompatInfo uses a Symfony http://symfony.com/doc/current/components/event_dispatcher/index.html[EventDispatcher] Component
to allow you to easily extend the features list.

The EventDispatcher component allow [label label-primary]#CompatInfo# components
to communicate with each other by dispatching events and listening to them.

=== Event Dispatcher

[label label-primary]#CompatInfo# implement interface `Bartlett\Reflect\Event\DispatcherInterface`.
You can add event listeners and event subscribers to this object.

[horizontal]
listeners::
Callable functions that are registered on an event dispatcher for specific events.

subscribers::
Classes that tell an event dispatcher what methods to listen to and what functions on the class
to invoke when the event is triggered. Event subscribers subscribe event listeners to an event dispatcher.

=== Getting an EventDispatcher

You can get the EventDispatcher of `Bartlett\Reflect\Event\DispatcherInterface`
by calling the +getEventDispatcher()+ method.

Here is an example :

[source,php]
----
<?php

use Bartlett\Reflect\Client;

// creates an instance of client
$client = new Client();

// request for a Bartlett\Reflect\Api\Analyser
$api = $client->api('analyser');

$dispatcher = $api->getEventDispatcher();
----

=== Adding Event Listeners

After you have the event dispatcher, you can register event listeners that listen
to specific events.

.Add a listener that will echo out files when they are parsed
====
[source,php]
----
<?php

use Bartlett\Reflect\Client;

use Symfony\Component\EventDispatcher\GenericEvent;

// creates an instance of client
$client = new Client();

// request for a Bartlett\Reflect\Api\Analyser
$api = $client->api('analyser');

$dispatcher = $api->getEventDispatcher();

$dispatcher->addListener(
    'reflect.progress',
    function (GenericEvent $e) {
        printf(
            'Parsing Data source "%s" in progress ... File "%s"' . PHP_EOL,
            $e['source'],
            $e['file']->getPathname()
        );
    }
);
----
====


=== Event Subscribers

Event subscribers are classes that implement interface `Symfony\Component\EventDispatcher\EventSubscriberInterface`.
They are used to register one or more event listeners to methods of the class.
Event subscribers tell event dispatcher exactly which events to listen to and what method to invoke on the class.

[label label-primary]#CompatInfo# plugins follow the event subscribers behaviors.
Have a look on NotifierPlugin :

[source,php]
----
<?php

use Bartlett\Reflect\Events;

class NotifierPlugin implements PluginInterface, EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        $events = array(
            Events::PROGRESS => 'onNotification',
            Events::ERROR    => 'onNotification',
            Events::COMPLETE => 'onNotification',
        );
        return $events;
    }
}
----

This plugin registers event listeners to the `reflect.complete` event
of a [label label-primary]#Reflect# parse request.

When the `reflect.complete` event is emitted, the +onNotification+ instance method
of the plugin is invoked.

=== Events lifecycle

[options="header,autowidth", cols="3,5,3", role="table table-bordered table-striped"]
|===========================
| Event | Action | Informations available

| reflect.progess  | Before to parse a new file of the data source.
|
`source` data source identifier or its alias
+
`file` current file parsed in the data source

| reflect.success | After parsing the current file ( A cached request will not trigger this event )
|
`source` data source identifier or its alias
+
`file` current file parsed in the data source
+
`ast` the http://en.wikipedia.org/wiki/Abstract_syntax_tree[Abstract Syntax Tree] result of https://github.com/nikic/PHP-Parser[PHP-Parser]

| reflect.error | When PHP Parser raise an error
|
`source` data source identifier or its alias
+
`file` current file parsed in the data source
+
`error` PHP Parser error message

| reflect.complete | When a parse request is over.
|
`source` data source identifier or its alias

|===========================


== Register Plugins

[NOTE]
==========
In [label label-primary]#Reflect# API 2, and other SAPI than CLI,
you have to register a plugin, if you want to use it.

In [label label-primary]#Reflect# API 3, it's no more necessary.
All valid plugins defined in the JSON configuration file are automatically registered.
==========

IMPORTANT: You must define environment variables `BARTLETT_SCAN_DIR` and `BARTLETTRC`,
otherwise the JSON config file will not found it.

If you don't want to use any plugins, and de-activated all at once, follow this pattern.

[source,php]
----
<?php

use Bartlett\Reflect\Environment;
use Bartlett\Reflect\Client;

// set default values for BARTLETT_SCAN_DIR
Environment::setScanDir()

// set default value for BARTLETTRC
putenv("BARTLETTRC=phpcompatinfo.json");

// creates an instance of client
$client = new Client();

// request for a Bartlett\Reflect\Api\Analyser
$api = $client->api('analyser');

// de activate all plugins
$api->activatePlugins(false);

// perform request, on a data source with default analyser (compatibility)
$dataSource = dirname(__DIR__) . '/src';
$analysers  = array('compatibility');

// equivalent to CLI command `phpcompatinfo analyser:run ../src`
$metrics = $api->run($dataSource, $analysers);
----
