= License
:description: The full details of how CompatInfo is licensed.
:jumbotron:
:icons!:
:iconsfont: font-awesome
:iconsfontdir: ./fonts/font-awesome
include::revision.asciidoc[]
include::attributes.asciidoc[]

[role="lead"]
[label label-primary]#CompatInfo# is open source.
You can use it for commercial projects, and open source projects.

== Documentation Licence

All documentation files (extension +.asciidoc+) provided in +docs+ folder are 
in http://asciidoc.org[AsciiDoc] format. They are built with a Python AsciiDoc backend 
maintained by myself, that convert output to an html http:/getbootstrap.com[Bootstrap] renders. 
http://laurent-laville.org/asciidoc/bootstrap/manual/current/en/[AsciiDoc-Bootstrap] 
is released under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2] license.

== Source License

As previous API 2.0, the source code is still under the 
http://opensource.org/licenses/BSD-3-Clause[BSD 3-Clause] license.

== Credits

I would like to thanks here specially a guy without who this PHP QA tool
won't be born.

[quote, Davey Shafik, http://daveyshafik.com/]
____
Original author, he introduced his http://pear.php.net/pepr/pepr-proposal-show.php?id=27[proposal]
in 2004, that gave birth of a PEAR package named
http://pear.php.net/package/PHP_CompatInfo[PHP_CompatInfo].
____

I would also like to thanks a guy who help me to enhance support of more than 50 extensions.

[quote, Remi Collet, http://blog.famillecollet.com/]
____
Contributor of many extensions reference and unit tests. He has joined the team
on version 2.0.0RC2
____
