= Configuration file
:description: How to customize the command line interface
include::revision.asciidoc[]
include::attributes.asciidoc[]
:iconsfont:   font-awesome
:jumbotron:
:jumbotron-fullwidth:
:footer:
:footer-fullwidth:


== Global options

* File extensions was restricted by default in both versions to +php+, +inc+ and +html+.

WARNING: In [label label-primary]#CompatInfo# 3.2, the Finder recursively traverse directories,
while it's not true in version 2.26

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo
    recursive="false"
    fileExtensions="php, inc, phtml"
    >

    <!-- ... -->
</phpcompatinfo>
----

[role="col-md-6"]
.JSON configuration [label label-primary]#3.2#
----
{
    "source-providers": [
        {
            "in": ". as current",
            "name": "/\\.(php|inc|phtml)$/"
        }
    ],
}
----

unfloat::[]

* Progress bar

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo
    consoleProgress="true"
    verbose="false"
    >

    <!-- ... -->
</phpcompatinfo>
----

[role="col-md-6"]
Use the first verbose level (+-v+) with +phpcompatinfo+ while running the `analyser:run` command.

unfloat::[]

* Caching results

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo
    cacheDriver="file"
    >

    <!-- ... -->
</phpcompatinfo>
----

[role="col-md-6"]
====
WARNING: Version [label label-primary]#3.2# is able to cache parsing results only with other SAPI than CLI.
See the Developer Guide.
====

== Cache options

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <cache id="file">
        <options>
            <gc_probability>1</gc_probability>
            <gc_maxlifetime>86400</gc_maxlifetime>
        </options>
    </cache>

</phpcompatinfo>
----

[role="col-md-6"]
====
CAUTION: Version [label label-primary]#3.2# does not provide yet ability to cache parsing results in CLI mode.
====


== References options

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <references>
        <reference name="Core" />
        <reference name="standard" />
    </references>

</phpcompatinfo>
----

[role="col-md-6"]
====
CAUTION: Version [label label-primary]#3.2# does not provide ability to load reference depending of rules in the configuration file.

All references are either pre-loaded (Prefetch Strategy) or loaded only when detected (AutoDiscover Strategy).

ifdef::basebackend-docbook[]
See xref:_references[]
endif::basebackend-docbook[]
ifdef::basebackend-html[]
See link:references.html[References] details.
endif::basebackend-html[]
====


== PHP settings

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <php>
        <ini name="memory_limit" value="140M" />
        <ini name="short_open_tag" />
        <ini name="zend.ze1_compatibility_mode" value="false" />
    </php>

</phpcompatinfo>
----

[role="col-md-6"]
====
CAUTION: Version [label label-primary]#3.2# does not provide ability to change PHP settings at run-time.
====


== Excluding Files or Elements from parsing

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <excludes>
        <exclude id="demo">
            <directory name=".*\/Zend\/.*" />
            <file name=".*\.php5" />
            <extension name="xdebug" />
            <interface name="SplSubject" />
            <trait name="^S" />
            <class name=".*Compat.*" />
            <function name="ereg.*" />
            <function name="debug_print_backtrace" />
            <constant name="T_USE" />
        </exclude>
    </excludes>

</phpcompatinfo>
----

[role="col-md-6"]
====
WARNING: Version [label label-primary]#3.2# does not provide ability to exclude elements (class, trait, ...),
but you can exclude files or directories with the Finder. See `source-providers` in the JSON
ifdef::basebackend-docbook[]
configuration file. See xref:_the_json_configuration_file[]
endif::basebackend-docbook[]
ifdef::basebackend-html[]
link:user-guide&#45;&#45;configuration.html[configuration] file.
endif::basebackend-html[]
====


== Listeners

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <listeners>
        <listener class="className" file="/path/to/filename">
            <arguments>
            </arguments>
        </listener>
    </listeners>

</phpcompatinfo>
----

[role="col-md-6"]
====
NOTE: Version [label label-primary]#3.2# provide this feature with the Symfony EventDispatcher component.

See
ifdef::basebackend-html[]
link:developer-guide&#45;&#45;plugins.html[plugins] section in the Developer Guide for details about
http://en.wikipedia.org/wiki/Event-driven_architecture[Event-Driven Architecture].
endif::basebackend-html[]
====


== Plugins options

[role="col-md-6"]
[source,xml]
.XML configuration [label label-success]#2.26#
----
<?xml version="1.0" encoding="utf-8" ?>
<phpcompatinfo>

    <plugins>
        <reference name="MyReference"
            class="PEAR_CompatInfo"
            file="/path/to/PEARCompatInfo.php">
            <arguments>
            </arguments>
        </reference>
    </plugins>

</phpcompatinfo>
----

[role="col-md-6"]
====
CAUTION: Version [label label-primary]#3.2# does not provide ability to select a custom References list.

All references are either pre-loaded (Prefetch Strategy) or loaded only when detected (AutoDiscover Strategy).

ifdef::basebackend-docbook[]
See xref:_references[]
endif::basebackend-docbook[]
ifdef::basebackend-html[]
See link:references.html[References] details.
endif::basebackend-html[]
====
