= CLI
:description: Command-Line Interface
include::revision.asciidoc[]
include::attributes.asciidoc[]


== Progress Bar

With adoption of *Symfony/Console* [label label-primary]#2.5# or greater, the progress bar feature 
is used instead of the progress bar helper.

The progress bar is displayed only if you invoke commands with the +--progress+ option.

For example :
[source,bash]
----
$ phpcompatinfo --progress analyser:run <SOURCE>
----

Renders depends of verbosity level. 

For example, on verbose level 1, progress will be displayed as a throbber:
[role="output"]
----
        8 [-------->-------------------]  1 sec
----

For example, on verbose level 2:
[role="output"]
----
    7  1 sec File Bartlett\CompatInfo\Console\Formatter\CompatibilityOutputFormatter.php in progress...
----

For example, on verbose level 3:
[role="output"]
----
    4  1 sec 6.8 MiB File Bartlett\CompatInfo\Analyser\CompatibilityAnalyser.php in progress...
----


== References

If we want to display list of references supported, here is how to do with both versions :

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:list
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:list
----

Now, if you want to details each reference one by one identified by its name (+<REF>+ in following examples), and got :

* Releases

[role="col-md-6"]
====
CAUTION: Feature not provided by version [label label-success]#3.2#
====

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --releases <REF>
----

unfloat::[]

* Interfaces

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:show --interfaces <REF>
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --interfaces <REF>
----

unfloat::[]

* Classes

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:show --classes <REF>
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --classes <REF>
----

unfloat::[]

* Functions

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:show --functions <REF>
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --functions <REF>
----

unfloat::[]

* Constants

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:show --constants <REF>
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --constants <REF>
----

unfloat::[]

* INI entries

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo reference:show --ini <REF>
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo reference:show --ini <REF>
----


== Print parses results

Where +<SOURCE>+ identify the data source, directly or via the JSON configuration file.

[role="col-md-6"]
[source,bash]
.Version [label label-success]#3.2#
----
$ phpcompatinfo analyser:run <SOURCE> --php
----

[role="col-md-6"]
[source,bash]
.Version [label label-primary]#4.0#
----
$ phpcompatinfo analyser:run <SOURCE>
----


== Caching results

[CAUTION] 
=====
* Version [label label-success]#3.2# may cache results to speed-up later analysis.
* Version [label label-primary]#4.0# is also able to cache results.
+
But it seems not necessary, especially if you unload +xdebug+ extension (that slows down execution at least by 50%).
=====
