= PHPCOMPATINFO(1)
:doctype:     manpage
include::revision.asciidoc[]
include::attributes.asciidoc[]
:author!:


== NAME
phpcompatinfo - PHP library that parse any data source to find out the minimum version and extensions required for it to run.


== SYNOPSIS
*phpcompatinfo* ['options'] 'command' ['arguments']


== DESCRIPTION
The phpcompatinfo(1) command parse any data source, defined in a json configuration file, to find out
elements, such as classes, interfaces, functions, constants, namespaces.


== OPTIONS
*-h, --help*::
    Display this help message.

*-q, --quiet*::
    Do not output any message.

*-v|vv|v, --verbose*::
    Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.

*-V, --version*::
    Display this application version.

*--ansi*::
    Force ANSI output.

*--no-ansi*::
    Disable ANSI output.

*--profile*::
    Display timing and memory usage information.

*--progress*::
    Show progress bar.

*--output*::
    Write results to file or URL.

*--manifest*::
   Show which versions of dependencies are bundled (PHAR version only).


== analyser:list COMMAND
The phpcompatinfo(1) 'analyser:list' command is used to show what analysers are installed
(see <<X1,CONF FILES>> section).


== analyser:run COMMAND
The phpcompatinfo(1) 'analyser:run' command is used to analyse a data source and display results.

Usage:

  phpcompatinfo analyser:run [--alias] [--format[="..."]] [--filter[="..."]] source [analysers1] ... [analysersN]

Where:

*--alias*::
  If set, the source refers to its alias

*--format*::
  If set, convert result to a specific format. (default: false)

*--filter*::
  Resource that provide a closure to filter results. (default: false)

*source*::
  Identify a data source; may be declared in a json configuration file (see <<X1,CONF FILES>> section)

*analysers1* ... *analysersN*::
  Identify one or more analyser to execute. See 'analyser:list' command to know what analysers are available.
  (default: ["compatibility"])


== config:validate COMMAND
The phpcompatinfo(1) 'config:validate' command is used to check syntax of your json configuration file

Usage:

  phpcompatinfo config:validate [file]

Where:

*file*::
  Path to `phpcompatinfo.json` file (optional)


== diagnose:run COMMAND
The phpcompatinfo(1) 'diagnose:run' command is used to identify common errors on a platform.

Usage:

  phpcompatinfo diagnose:run [-vv|-vvv]


== diagram:class COMMAND
The phpcompatinfo(1) 'diagram:class' command is used to generate diagram about a user class present in a data source

Usage:

  phpcompatinfo diagram:class [--alias] [--engine[="..."]] argument source

Where:

*argument*::
  Name of the class to inspect

*source*::
  Identify a data source; may be declared in a json configuration file (see <<X1,CONF FILES>> section)

*--alias*::
  If set, the source refers to its alias

*--engine*::
  Graphical syntax. (default: "plantuml")


== diagram:package COMMAND
The phpcompatinfo(1) 'diagram:package' command is used to generate diagram about namespaces in a data source

Usage:

  phpcompatinfo diagram:package [--alias] [--engine[="..."]] source

Where:

*source*::
  Identify a data source; may be declared in a json configuration file (see <<X1,CONF FILES>> section)

*--alias*::
  If set, the source refers to its alias

*--engine*::
  Graphical syntax. (default: "plantuml")


== plugin:list COMMAND
The phpcompatinfo(1) 'plugin:list' command is used to show what plugins are installed
(see <<X1,CONF FILES>> section).


== reference:list COMMAND
The phpcompatinfo(1) 'reference:list' command is used to list all references supported.

Usage:

  phpcompatinfo reference:list


== reference:show COMMAND
The phpcompatinfo(1) 'reference:show' command is used to introspect a reference.

Usage:

  phpcompatinfo reference:show [--filter[="..."]] [--releases] [--ini] [--constants] [--functions] [--interfaces] [--classes] name

Where:

*name*::
  Introspection of a reference (case insensitive)

*--filter*::
  Resource that provide a closure to filter results (default: false)

*--releases*::
  Show releases

*--ini*::
  Show ini Entries

*--constants*::
  Show constants

*--functions*::
  Show functions

*--interfaces*::
  Show interfaces

*--classes*::
  Show classes


== reflection:class COMMAND
The phpcompatinfo(1) 'reflection:class' command is used to give information about a user class present in a data source.

Usage:

  phpcompatinfo reflection:class [--alias] [--return="..."] argument source

Where:

*argument*::
  Name of the class to reflect.

*source*::
  Identify a data source; may be declared in a json configuration file (see <<X1,CONF FILES>> section)

*--alias*::
  If set, the source refers to its alias

*--format*::
  Format of result to return. False when raw text. (default: false)


== reflection:function COMMAND
The phpcompatinfo(1) 'reflection:function' command is used to give information about a user function present in a data source.

Usage:

  phpcompatinfo reflection:function [--alias] [--return="..."] argument source

Where:

*argument*::
  Name of the function to reflect.

*source*::
  Identify a data source; may be declared in a json configuration file (see <<X1,CONF FILES>> section)

*--alias*::
  If set, the source refers to its alias

*--format*::
  Format of result to return. False when raw text. (default: false)


== EXIT STATUS
*0*::
    Success

*1*::
    Failure (syntax or usage error; configuration error; unexpected error).

[[X1]]
== CONF FILES
A configuration file contains data sources that can be analysed, but also optional plugins and analysers installed.
Require configuration file is loaded in the following order:

. The CONF_FILE specified by the environment variables `BARTLETTRC` and `BARTLETT_SCAN_DIR`.
. `phpcompatinfo.json` from the current directory.
. `phpcompatinfo.json` from the User `$HOME/.config` directory.
. `phpcompatinfo.json` from the `/etc` directory.


== BUGS
Report any issue at <https://github.com/llaville/php-compat-info/issues>


== AUTHORS
PHP_CompatInfo was originally written by Davey Shafik in 2004.

Remi Collet, contributor of many extensions reference and unit tests, joined the project since version 2.0.0RC2

The Command-Line Interface (CLI) version was introduced in version 2.0 and is written by Laurent Laville.


== SEE ALSO
Main web site: <http://php5.laurent-laville.org/compatinfo/>


== COPYRIGHT
Copyright \(C) 2010-2015 Laurent Laville.


== LICENSE
Free use of this software is granted under the terms of the BSD 3-clause license.
