= Setup
:description: Configuring your project and get ready for your first analyse.
:jumbotron:
:icons!:
:iconsfont: font-awesome
:iconsfontdir: ./fonts/font-awesome
include::revision.asciidoc[]
include::attributes.asciidoc[]


== Install

[role="lead"]
CompatInfo may be installed in several ways, choose your favorite.

[role="partintro",cols="3,9"]
.icon:download[size="7x"] [clearfix]#CompatInfo takes advantage of new features in PHP 5.3 or greater.#
--
[medium]*Minimal Requirements*

Before you install PHP [label label-primary]#CompatInfo#, you will need an operating system
with http://www.php.net[PHP] 5.3.0 or later installed,
and four loaded extensions:
http://www.php.net/manual/en/book.reflection.php[Reflection],
http://www.php.net/manual/en/book.tokenizer.php[tokenizer],
http://www.php.net/manual/en/book.pcre.php[pcre],
http://www.php.net/manual/en/book.spl.php[SPL].

[medium]*Using PEAR*

As PHP-Parser 1.0 is not planned to be distributed as a PEAR package
(https://github.com/nikic/PHP-Parser/issues/97[read discussion]), CompatInfo 3.0 will not be available on
the http://bartlett.laurent-laville.org[PEAR Bartlett Channel].

[medium]*Using Composer*

Put a file named [label label-default]#composer.json# at the root of your project,
with at least, content below:
----
{
    "require": {
        "bartlett/php-compatinfo": ">=3.0"
    },
    "minimum-stability": "beta"    
}
----
And run the following command:
----
$ php composer.phar install
----

[medium]*Using PHP Archive (phar)*

----
wget http://bartlett.laurent-laville.org/get/phpcompatinfo.phar
chmod +x phpcompatinfo.phar
----
--

== Autoloaders

[role="lead"]
CompatInfo does not provides any native autoloader.

It's up to you to choose what is be the best strategy :

* If you have installed [label label-primary]#CompatInfo# with http://getcomposer.org/[Composer],
it must have generated a `vendor/autoload.php` file you should used.
* If you use the phar version, you don't need autoloader, all dependencies are embeded.
* The basic PHP version requires an autoloader that can load classes that follow
the http://www.php-fig.org/psr/psr-0/[PSR-0] class naming standard.

NOTE: I recommend using Symfony http://symfony.com/doc/current/components/class_loader/index.html[ClassLoader] component.

Here are a minimum example, if you used a forked copy of GitHub source.

[source,php]
.Symfony UniversalClassLoader
----
<?php
require_once 'Symfony/Component/ClassLoader/UniversalClassLoader.php';

use Symfony\Component\ClassLoader\UniversalClassLoader;

$loader = new UniversalClassLoader();
$loader->registerNamespaces(array(
    'Symfony\\Component\\Finder'          => $vendorDir . '/symfony/finder',
    'Symfony\\Component\\EventDispatcher' => $vendorDir . '/symfony/event-dispatcher',
    'Symfony\\Component\\Console'         => $vendorDir . '/symfony/console',
    'Symfony\\Component\\ClassLoader'     => $vendorDir . '/symfony/class-loader',
    'Bartlett\\Reflect'                   => $vendorDir . '/bartlett/php-reflect/src',
    'Bartlett\\Tests\\CompatInfo'         => $baseDir . '/tests',
    'Bartlett'                            => $baseDir . '/src',
));
$loader->register();
----

You are now ready to analyse your first data source.

link:quick-start.html["Go to next chapter: Quick Start",role="primary",icon="glyphicon-step-forward",options="block"]
