ifndef::basebackend-docbook[]

= User Guide
:description: Installing PHP CompatInfo
include::revision.asciidoc[]
include::attributes.asciidoc[]

endif::basebackend-docbook[]

== Installation

[role="lead"]
CompatInfo may be installed in several ways, choose your favorite.

WARNING: Please read the
ifdef::basebackend-bootstrap[]
link:migration-guide-3.html[migration guide v3]
endif::basebackend-bootstrap[]
ifdef::basebackend-docbook[]
xref:_migration_guide_v3[]
endif::basebackend-docbook[]
in case you are upgrading from a version 2.x of PHP CompatInfo.

=== Requirements

Before you install PHP [label label-primary]#CompatInfo#, you will need an operating system
with http://www.php.net[PHP] 5.3.2 or later installed,

[label label-primary]#CompatInfo# requires the
http://www.php.net/manual/en/book.json.php[json],
http://www.php.net/manual/en/book.libxml.php[libxml],
http://www.php.net/manual/en/book.pdo.php[pdo] (http://www.php.net/manual/en/ref.pdo-sqlite.php[sqlite driver]),
http://www.php.net/manual/en/book.pcre.php[pcre], and
http://www.php.net/manual/en/book.spl.php[spl] extensions.
These extensions are usually compiled and enabled by default.

=== Composer

Put a file named [label label-default]#composer.json# at the root of your project, with the content below:
[source,json]
----
{
    "require": {
        "bartlett/php-compatinfo": "4.3.0"
    }
}
----
And ask http://getcomposer.org/[Composer] to install the dependencies:
[source,bash]
----
$ php composer.phar install
----

[TIP]
====
With composer `install` or `create-project` commands,
if you want to disable installation of require-dev packages
(`doctrine/cache`, `psr/log`, `monolog/monolog`, `bartlett/phpunit-loggertestlistener`),
don't forget to specify the `--no-dev` option.
====

[TIP]
====
You can also use Composer to create a new project from an existing [label label-primary]#CompatInfo# package.
This is the equivalent of doing a git clone checkout followed by a composer install of the vendors.

[source,bash]
----
$ php composer.phar create-project bartlett/php-compatinfo /path/to/install 4.3.0
----
Where +/path/to/install+ is your install directory.
====

=== PHAR

The recommended way for newbies, or just to have a look on features of this library, is to download
a PHP Archive that contain all required dependencies of PHP [label label-primary]#CompatInfo#
bundled in a single file.

[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/phpcompatinfo-4.3.0.phar
$ chmod +x phpcompatinfo-4.3.0.phar
$ mv phpcompatinfo-4.3.0.phar /usr/local/bin/phpcompatinfo
$ phpcompatinfo
----

You can also immediately use the PHAR after you have downloaded it.
[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/phpcompatinfo-4.3.0.phar
$ php phpcompatinfo-4.3.0.phar
----

ifdef::basebackend-bootstrap[]
== Next

link:user-guide&#45;&#45;configuration.html["Configuring PHP CompatInfo",role="primary",icon="glyphicon-step-forward",options="block"]
endif::basebackend-bootstrap[]
