ifndef::basebackend-docbook[]

= User Guide
:description: Installing PHP CompatInfo
include::revision.asciidoc[]
include::attributes.asciidoc[]
:icons!:
:iconsfont:   font-awesome
:jumbotron:
:jumbotron-fullwidth:
:footer:
:footer-fullwidth:

endif::basebackend-docbook[]

== Installation

[role="lead"]
CompatInfo may be installed in several ways, choose your favorite.

WARNING: Please read the
ifdef::basebackend-bootstrap[]
link:migration-guide.html[migration guide]
endif::basebackend-bootstrap[]
ifdef::basebackend-docbook[]
xref:_migration_guide[]
endif::basebackend-docbook[]
in case you are upgrading from a version 2.x of PHP CompatInfo.

=== Requirements

Before you install PHP [label label-primary]#CompatInfo#, you will need an operating system
with http://www.php.net[PHP] 5.3.0 or later installed,

[label label-primary]#CompatInfo# requires the
http://www.php.net/manual/en/book.json.php[json],
http://www.php.net/manual/en/book.libxml.php[libxml],
http://www.php.net/manual/en/book.pcre.php[pcre], and
http://www.php.net/manual/en/book.spl.php[spl] extensions.
These extensions are usually compiled and enabled by default.

=== Composer

Put a file named [label label-default]#composer.json# at the root of your project, with the content below:
[source,json]
----
{
    "require": {
        "bartlett/php-compatinfo": "~3.3"
    }
}
----
And ask http://getcomposer.org/[Composer] to install the dependencies:
[source,bash]
----
$ php composer.phar install
----

[TIP]
====
You can also use Composer to create a new project from an existing [label label-primary]#CompatInfo# package.
This is the equivalent of doing a git clone checkout followed by a composer install of the vendors.

[source,bash]
----
$ php composer.phar create-project bartlett/php-compatinfo path 3.3.0
----
Where +path+ is your install directory.
====

=== PHAR

The recommended way for newbies, or just to have a look on features of this library, is to download
a PHP Archive that contain all required dependencies of PHP [label label-primary]#CompatInfo#
bundled in a single file.

[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/phpcompatinfo-3.3.0-beta.phar
$ chmod +x phpcompatinfo-3.3.0-beta.phar
$ mv phpcompatinfo-3.3.0-beta.phar /usr/local/bin/phpcompatinfo
$ phpcompatinfo
----

You can also immediately use the PHAR after you have downloaded it.
[source,bash]
----
$ wget http://bartlett.laurent-laville.org/get/phpcompatinfo-3.3.0-beta.phar
$ php phpcompatinfo-3.3.0-beta.phar
----

ifdef::basebackend-bootstrap[]
== Next

link:user-guide&#45;&#45;configuration.html["Configuring PHP CompatInfo",role="primary",icon="glyphicon-step-forward",options="block"]
endif::basebackend-bootstrap[]
